- hosts: "ec2"
  tasks:
  - wait_for_connection: {}
  - name: Disable aos-3.9 repo
    command: yum-config-manager -q --disable aos-3.9
  - name: Enable aos-3.7 repo
    command: yum-config-manager -q --enable aos-3.7
